ALTER TABLE kn_menus ADD COLUMN IF NOT EXISTS items TEXT NULL;
ALTER TABLE kn_menu_items ADD COLUMN IF NOT EXISTS col TINYINT DEFAULT NULL;
ALTER TABLE kn_menu_items ADD COLUMN IF NOT EXISTS badge VARCHAR(50) DEFAULT '';
